# Generated by Django 3.0.3 on 2020-03-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre del articulo')),
                ('stock', models.IntegerField(verbose_name='Cantidad del articulo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del articulo')),
                ('description', models.TextField(verbose_name='Descripcion del articulo')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
