# Generated by Django 3.0.3 on 2020-03-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_text', models.CharField(max_length=255, verbose_name='texto de entrada')),
                ('date_text', models.DateField(auto_now_add=True, verbose_name='fecha de entrada')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_text', models.CharField(max_length=255, verbose_name='Salida de texto')),
                ('date_text', models.DateField(auto_now_add=True, verbose_name='fecha de salida')),
                ('entry_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Entry')),
            ],
            options={
                'verbose_name': 'Output',
                'verbose_name_plural': 'Outputs',
            },
        ),
    ]
