# Generated by Django 3.0.4 on 2020-03-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20200306_1928'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulos.Article'),
        ),
    ]
